services:
  workhub-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      API_HOST: host.docker.internal
      API_PORT: 3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
